################### {Beat} Configuration Example #########################

############################# {Beat} ######################################

discordbeat:
  # Specifies bot token to login to Discord with
  token: "INSERT-TOKEN-HERE"

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
